"""Consolidated initial migration

Revision ID: 834164764f9a
Revises: 
Create Date: 2026-02-24 02:45:29.320076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '834164764f9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.alter_column('filtro',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.alter_column('substituto',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.alter_column('bloqueios',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.alter_column('somente_se_tiver',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
        batch_op.alter_column('filtro_midia',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   nullable=False,
                   existing_server_default=sa.text("'todos'"))

    with op.batch_alter_table('regra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filtro_midia', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.alter_column('converter_shopee',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regra', schema=None) as batch_op:
        batch_op.alter_column('converter_shopee',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('0'))
        batch_op.drop_column('filtro_midia')

    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.alter_column('filtro_midia',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   nullable=True,
                   existing_server_default=sa.text("'todos'"))
        batch_op.alter_column('somente_se_tiver',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        batch_op.alter_column('bloqueios',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        batch_op.alter_column('substituto',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        batch_op.alter_column('filtro',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    # ### end Alembic commands ###
