"""add_missing_ativo_columns

Revision ID: 90de375b1de2
Revises: 834164764f9a
Create Date: 2026-02-24 02:59:46.886477

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '90de375b1de2'
down_revision: Union[str, None] = '834164764f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionando 'ativo' se não existir
    try:
        op.add_column('bot', sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    except Exception: pass
    
    try:
        op.add_column('regra', sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    except Exception: pass
    
    try:
        op.add_column('agendamento', sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    except Exception: pass
    
    # Garantir que filtro_midia existe
    try:
        op.add_column('regra', sa.Column('filtro_midia', sa.String(), nullable=False, server_default=sa.text("'todos'")))
    except Exception: pass
    
    try:
        op.add_column('agendamento', sa.Column('filtro_midia', sa.String(), nullable=False, server_default=sa.text("'todos'")))
    except Exception: pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try: op.drop_column('bot', 'ativo')
    except Exception: pass
    try: op.drop_column('regra', 'ativo')
    except Exception: pass
    try: op.drop_column('agendamento', 'ativo')
    except Exception: pass
    try: op.drop_column('regra', 'filtro_midia')
    except Exception: pass
    try: op.drop_column('agendamento', 'filtro_midia')
    except Exception: pass
    # ### end Alembic commands ###
